[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt ="0.3"
aes = "0.7"
block-modes = "0.8"
rand = "0.8"
argon2 = "0.5.3"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

